use core::{run, error::Result};

fn main() -> Result<()> {
    run()
}
